import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../globals.css";
import VNavBar from "@/components/VNavBar";
import { Providers } from "@components/providers";
import SessionProvider from "@components/SessionProvider";
import { getServerSession } from "next-auth";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "StudyLab",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await getServerSession();

  return (
    <html lang="en">
      <body className="bg-gray-100 font-inter">
        <SessionProvider session={session}>
          <Providers>
            <div className="flex min-h-screen">
              <div className="justify-center items-center mr-7 my-auto">
                <VNavBar />
              </div>
              <div className="flex flex-col w-[87.5%] ">
                <div className="flex-1 border-gray-50 rounded-3xl my-11">
                  {children}
                </div>
              </div>
            </div>
          </Providers>
        </SessionProvider>
      </body>
    </html>
  );
}
