import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../globals.css";
import HNavbar from "@/components/HNavBar";
import { Providers } from "@components/providers";
import SessionProvider from "@components/SessionProvider";
import { getServerSession } from "next-auth";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "StudyLab",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await getServerSession();

  return (
    <html lang="en">
      <body className="font-inter">
        <SessionProvider session={session}>
          <Providers>
            <HNavbar />
            {children}
          </Providers>
        </SessionProvider>
      </body>
    </html>
  );
}
