import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../globals.css";
import HNavbar from "@/components/HNavBar";
import { Providers } from "./providers";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "StudyLab",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="bg-gray-100 font-inter">
        <Providers>
          <HNavbar />
          {children}
        </Providers>
      </body>
    </html>
  );
}
